### ISSUE TITLE
Alwas shows on Mobile (Chrome Android)

### ISSUE THREAD

**Issue by frostymarvelous** [buildo/react-cookie-banner#11] opened 2015-12-07 22:55 UTC
I haven't tested extensively.
It seems not to be working in Chrome for Android. Other browsers might be affected by I have not been able to check.

I click the Got it button, it hides but when I reload the page, it is shown again.

**Comment by FrancescoCioria** [comment] 2015-12-11 12:07
does this happens only when you close and reopen Chrome or also if you simply reload it?

Closing and reopening Chrome currently removes the cookie we're using to store user decision, so this is in fact an issue.

Simply reloading the page doesn't reset the `cookie-banner` on the phones I tested on (both `Android` and `iOS`). If this happens is likely because of some particular settings in you phone.

**Comment by FrancescoCioria** [comment] 2015-12-11 12:40
Ok, I think the problem is that the cookie has expiration date set to `Session`:
![image](https://cloud.githubusercontent.com/assets/4029499/11744005/a20e18bc-a00c-11e5-81e5-32b3a2a2f4ea.png)
and mobile browsers probably clear those cookies at every relaunch.

If this is the case it shouldn't be too hard too fix :)
I'll work on it

**Comment by frostymarvelous** [comment] 2015-12-12 07:09
Sadly, I can't check. My phone is gone for repairs but I suspect it is relaunch.
Glad you pinpointed the issue.

**Closed** 2016-02-11 12:12 UTC
